apiVersion: v1
kind: Service
metadata:
  name: geth-miner-service
  labels:
    name: geth-miner-service
spec:
  type: NodePort
  ports:
    - name: gethrpc
      protocol: TCP
      targetPort: 8180
    - name: geth
      protocol: TCP
      targetPort: 31303
  selector:
    name: geth-miner

